services:

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile

    container_name: agriai_backend

    ports:
      - "8000:8000"

    volumes:
      - ./backend:/app

    env_file:
      - .env

    depends_on:
      postgres:
        condition: service_healthy

    restart: unless-stopped


  postgres:
    image: postgres:16

    container_name: agriai_postgres

    environment:
      POSTGRES_DB: agriai
      POSTGRES_USER: agriai
      POSTGRES_PASSWORD: agriai_123456789

    ports:
      - "5433:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U agriai -d agriai"]
      interval: 5s
      timeout: 5s
      retries: 5

    restart: unless-stopped


volumes:
  postgres_data: